# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b5368dfb510196e713624b2683221ba2f028100d5ea4b43d27f7696408be6406ffda99c929f33249394e4fe0ba60f876ef1c465573041b3c5e704e4fdde722c9

test:
  secret_key_base: 60dd5d61f3cd14da0b071151d5ebb97d2ebe705d07fd3dfdeb523b3e216f51b6e206314b7be470a0a1ea9d519d3aaa380362602311021e2a3a71ef25713499fb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
